Alias: NPU = http://npu-terminology.org

ValueSet:      NPUCovid19RapidTests
Id:	   npu-covid-19-rapid-tests
Title:	       "NPU Rapid Test List (COVID-19)"
Description:   "Rapid Test List (COVID-19) from [NPU]"

// rapid ag tests
* NPU#NPU59310	"Secr(Nasoph)—Severe acute respiratory syndrome coronavirus 2(ag); arb.c.(proc.) = ?"
* NPU#NPU59312	"Secr(Vestibulum nasi)—Severe acute respiratory syndrome coronavirus 2(ag); arb.c.(proc.) = ?"
* NPU#NPU59385	"Syst(spec.)—Severe acute respiratory syndrome coronavirus 2(ag); arb.c.(proc.) = ?"
* NPU#NPU59386	"Secr(spec.)—Severe acute respiratory syndrome coronavirus 2(ag); arb.c.(proc.) = ?"
* NPU#NPU59387	"Secr(Pharynx)—Severe acute respiratory syndrome coronavirus 2(ag); arb.c.(proc.) = ?"
* NPU#NPU59388	"Saliva—Severe acute respiratory syndrome coronavirus 2(ag); arb.c.(proc.) = ?"
* NPU#NPU60223	"Secr(Oroph)—Severe acute respiratory syndrome coronavirus 2(ag); arb.c.(proc.) = ?"

ValueSet:      NPUCovid19NonRapidTests
Id:	   npu-covid-19-non-rapid-tests
Title:	       "NPU Test List, Non-Rapid (COVID-19)"
Description:   "Test List, Non-Rapid (COVID-19) from [NPU]"

// all covid-19 tests but the rapid ag tests
* NPU#NPU59097	"Syst(spec.)—Severe acute respiratory syndrome coronavirus 2(RNA); arb.c.(proc.) = ?"
* NPU#NPU59105	"Secr(Nasoph)—Severe acute respiratory syndrome coronavirus 2(RNA); arb.c.(proc.) = ?"
* NPU#NPU59106	"Secr(spec.)—Severe acute respiratory syndrome coronavirus 2(RNA); arb.c.(proc.) = ?"
* NPU#NPU59118	"Ex—Severe acute respiratory syndrome coronavirus 2(RNA); arb.c.(proc.) = ?"
* NPU#NPU59129	"Secr(Trachea)—Severe acute respiratory syndrome coronavirus 2(RNA); arb.c.(proc.) = ?"
* NPU#NPU59130	"BAL—Severe acute respiratory syndrome coronavirus 2(RNA); arb.c.(proc.) = ?"
* NPU#NPU59144	"P—Severe acute respiratory syndrome coronavirus 2 antibody; arb.c.(proc.) = ?"
* NPU#NPU59145	"P—Severe acute respiratory syndrome coronavirus 2 antibody; arb.subst.c.(proc.) = ? (p.d.u.)"
* NPU#NPU59146	"P—Severe acute respiratory syndrome coronavirus 2 antibody(IgM); arb.c.(proc.) = ?"
* NPU#NPU59147	"P—Severe acute respiratory syndrome coronavirus 2 antibody(IgG); arb.c.(proc.) = ?"
* NPU#NPU59148	"P—Severe acute respiratory syndrome coronavirus 2 antibody(IgM); arb.subst.c.(proc.) = ? (p.d.u.)"
* NPU#NPU59149	"P—Severe acute respiratory syndrome coronavirus 2 antibody(IgG); arb.subst.c.(proc.) = ? (p.d.u.)"
* NPU#NPU59150	"P—Severe acute respiratory syndrome coronavirus 2 antibody(IgA); arb.subst.c.(proc.) = ? (p.d.u.)"
* NPU#NPU59151	"P—Severe acute respiratory syndrome coronavirus 2 antibody(IgA); arb.c.(proc.) = ?"
* NPU#NPU59152	"P—Severe acute respiratory syndrome coronavirus 2 antibody; arb.c.(list; proc.)"
* NPU#NPU59178	"Secr(Pharynx)—Severe acute respiratory syndrome coronavirus 2(RNA); arb.c.(proc.) = ?"
* NPU#NPU59179	"U—Severe acute respiratory syndrome coronavirus 2(RNA); arb.c.(proc.) = ?"
* NPU#NPU59180	"F—Severe acute respiratory syndrome coronavirus 2(RNA); arb.cont.(proc.) = ?"
* NPU#NPU59191	"P—Severe acute respiratory syndrome coronavirus 2(RNA); arb.c.(proc.) = ?"
* NPU#NPU59226	"P—Severe acute respiratory syndrome coronavirus 2 antibody(neutralizing); arb.subst.c.(proc.) = ? (p.d.u.)"
* NPU#NPU59236	"Saliva—Severe acute respiratory syndrome coronavirus 2(RNA); arb.c.(proc.) = ?"
* NPU#NPU59244	"P—Severe acute respiratory syndrome coronavirus 2 antibody(IgG+IgM); arb.c.(proc.) = ?"
* NPU#NPU59283	"P—Severe acute respiratory syndrome coronavirus 2(RNA); arb.num.c.(proc.) = ? (p.d.u.)"
* NPU#NPU59285	"Syst(spec.)—Severe acute respiratory syndrome coronavirus 2(RNA); arb.num.c.(proc.) = ? (p.d.u.)"
* NPU#NPU59308	"Saliva—Severe acute respiratory syndrome coronavirus 2(ag); mass c. = ? ng/L"
* NPU#NPU59309	"P—Severe acute respiratory syndrome coronavirus 2(ag); mass c. = ? ng/L"
* NPU#NPU59311	"Secr(spec.)—Severe acute respiratory syndrome coronavirus 2(ag); mass c. = ? ng/L"
* NPU#NPU59330	"Csf—Severe acute respiratory syndrome coronavirus 2(RNA); arb.c.(proc.) = ?"
* NPU#NPU59331	"Tissue(spec.)—Severe acute respiratory syndrome coronavirus 2(RNA); arb.cont.(proc.) = ?"
* NPU#NPU59389	"BAL—Severe acute respiratory syndrome coronavirus 2(ag); arb.c.(proc.) = ?"
* NPU#NPU59808	"P—Severe acute respiratory syndrome coronavirus 2 (Spike glycoprotein) antibody; arb.c.(proc.) = ?"
* NPU#NPU59809	"P—Severe acute respiratory syndrome coronavirus 2 (Spike glycoprotein) antibody; arb.subst.c.(proc.) = ? (p.d.u.)"
* NPU#NPU59810	"P—Severe acute respiratory syndrome coronavirus 2 (Nucleoprotein) antibody; arb.c.(proc.) = ?"
* NPU#NPU59811	"P—Severe acute respiraNPU60268tory syndrome coronavirus 2 (Nucleoprotein) antibody; arb.subst.c.(proc.) = ? (p.d.u.)"
* NPU#NPU59828	"P—Severe acute respiratory syndrome coronavirus 2 (Nucleoprotein) antibody(IgA); arb.c.(proc.) = ?"
* NPU#NPU59829	"P—Severe acute respiratory syndrome coronavirus 2 (Nucleoprotein) antibody(IgA); arb.subst.c.(proc.) = ? (p.d.u.)"
* NPU#NPU59830	"P—Severe acute respiratory syndrome coronavirus 2 (Spike glycoprotein) antibody(IgA); arb.c.(proc.) = ?"
* NPU#NPU59831	"P—Severe acute respiratory syndrome coronavirus 2 (Spike glycoprotein) antibody(IgA); arb.subst.c.(proc.) = ? (p.d.u.)"
* NPU#NPU59832	"P—Severe acute respiratory syndrome coronavirus 2 (Nucleoprotein) antibody(IgG); arb.c.(proc.) = ?"
* NPU#NPU59833	"P—Severe acute respiratory syndrome coronavirus 2 (Nucleoprotein) antibody(IgG); arb.subst.c.(proc.) = ? (p.d.u.)"
* NPU#NPU59834	"P—Severe acute respiratory syndrome coronavirus 2 (Spike glycoprotein) antibody(IgG); arb.c.(proc.) = ?"
* NPU#NPU59835	"P—Severe acute respiratory syndrome coronavirus 2 (Spike glycoprotein) antibody(IgG); arb.subst.c.(proc.) = ? (p.d.u.)"
* NPU#NPU59836	"P—Severe acute respiratory syndrome coronavirus 2 (Nucleoprotein) antibody(IgM); arb.c.(proc.) = ?"
* NPU#NPU59837	"P—Severe acute respiratory syndrome coronavirus 2 (Nucleoprotein) antibody(IgM); arb.subst.c.(proc.) = ? (p.d.u.)"
* NPU#NPU59838	"P—Severe acute respiratory syndrome coronavirus 2 (Spike glycoprotein) antibody(IgM); arb.c.(proc.) = ?"
* NPU#NPU59839	"P—Severe acute respiratory syndrome coronavirus 2 (Spike glycoprotein) antibody(IgM); arb.subst.c.(proc.) = ? (p.d.u.)"
* NPU#NPU59953	"Saliva—Severe acute respiratory syndrome coronavirus 2, Spike glycoprotein(ag); mass c. = ? ng/L"
* NPU#NPU59954	"P—Severe acute respiratory syndrome coronavirus 2, Spike glycoprotein(ag); mass c. = ? ng/L"
* NPU#NPU59955	"Secr(Nasoph)—Severe acute respiratory syndrome coronavirus 2, Spike glycoprotein(ag); arb.c.(proc.) = ?"
* NPU#NPU59956	"Secr(spec.)—Severe acute respiratory syndrome coronavirus 2, Spike glycoprotein(ag); mass c. = ? ng/L"
* NPU#NPU59957	"Secr(Nasoph)—Severe acute respiratory syndrome coronavirus 2, Nucleoprotein(ag); arb.c.(proc.) = ?"
* NPU#NPU59958	"P—Severe acute respiratory syndrome coronavirus 2, Nucleoprotein(ag); mass c. = ? ng/L"
* NPU#NPU59959	"Secr(spec.)—Severe acute respiratory syndrome coronavirus 2, Nucleoprotein(ag); mass c. = ? ng/L"
* NPU#NPU59960	"Saliva—Severe acute respiratory syndrome coronavirus 2, Nucleoprotein(ag); mass c. = ? ng/L"
* NPU#NPU59962	"Csf—Severe acute respiratory syndrome coronavirus 2 (Spike glycoprotein) antibody; arb.c.(proc.) = ?"
* NPU#NPU60214	"Syst(spec.)—Severe acute respiratory syndrome coronavirus 2(B.1.1.7; RNA); arb.c.(proc.) = ?"
* NPU#NPU60215	"Syst(spec.)—Severe acute respiratory syndrome coronavirus 2(B.1.351; RNA); arb.c.(proc.) = ?"
* NPU#NPU60216	"Syst(spec.)—Severe acute respiratory syndrome coronavirus 2(B.1.1.28.1; RNA); arb.c.(proc.) = ?"
* NPU#NPU60218	"Syst(spec.)—Severe acute respiratory syndrome coronavirus 2(RNA); variation(proc.) = ?"
* NPU#NPU60217	"Syst(spec.)—Genome(SARS-CoV-2); seq.var.(proc.) = ?"
* NPU#NPU60218	"Syst(spec.)—Severe acute respiratory syndrome coronavirus 2(RNA); variation(proc.) = ?"
* NPU#NPU60268  "Syst(spec.)—Severe acute respiratory syndrome coronavirus 2(RNA; S gene); seq.var.(proc) = ?"


