Instance: t
InstanceOf: StructureDefinition
Description: "Test Group"
Title: "Test Group"
Usage: #definition
* publisher = "HL7 Europe"
* status = #draft
* url = "http://hl7.eu/fhir/ig/dcc/StructureDefinition/t"
* name = "t"
* title = "Test Group"
* status = #draft
* experimental = true
* description = "Test Group"
* version = "0.0.1"
* mapping[0].identity = "fhir"
* mapping[0].uri = "hl7.org/fhir/r4"
* mapping[0].name = "FHIR"
* kind = #logical
* abstract = true
* type = "t"
* baseDefinition = "http://hl7.org/fhir/StructureDefinition/Element"
* derivation = #specialization
* differential.element[0].id = "t"
* differential.element[0].path = "t"
* differential.element[0].short = "Test Group"
* differential.element[0].definition = "Test Group"
* differential.element[0].min = 1
* differential.element[0].max = "1"
* differential.element[1].id = "t.tg"
* differential.element[1].path = "t.tg"
* differential.element[1].short = "disease or agent targeted"
* differential.element[1].definition = "disease or agent targeted"
* differential.element[1].min = 1
* differential.element[1].max = "1"
* differential.element[1].type.code = #code
* differential.element[2].id = "t.tt"
* differential.element[2].path = "t.tt"
* differential.element[2].short = "Type of Test"
* differential.element[2].definition = "Type of Test"
* differential.element[2].min = 1
* differential.element[2].max = "1"
* differential.element[2].type.code = #code
* differential.element[3].id = "t.sc"
* differential.element[3].path = "t.sc"
* differential.element[3].short = "NAA Test Name"
* differential.element[3].definition = "NAA Test Name"
* differential.element[3].min = 1
* differential.element[3].max = "1"
* differential.element[3].type.code = #string
* differential.element[4].id = "t.tr"
* differential.element[4].path = "t.tr"
* differential.element[4].short = "RAT Test name and manufacturer"
* differential.element[4].definition = "RAT Test name and manufacturer"
* differential.element[4].min = 1
* differential.element[4].max = "1"
* differential.element[4].type.code = #code
* differential.element[5].id = "t.co"
* differential.element[5].path = "t.co"
* differential.element[5].short = "Date/Time of Sample Collection"
* differential.element[5].definition = "Date/Time of Sample Collection"
* differential.element[5].min = 1
* differential.element[5].max = "1"
* differential.element[5].type.code = #dateTime
* differential.element[6].id = "t.is"
* differential.element[6].path = "t.is"
* differential.element[6].short = "Test Result"
* differential.element[6].definition = "Test Result"
* differential.element[6].min = 1
* differential.element[6].max = "1"
* differential.element[6].type.code = #code
* differential.element[7].id = "t.ci"
* differential.element[7].path = "t.ci"
* differential.element[7].short = "Testing Centre"
* differential.element[7].definition = "Testing Centre"
* differential.element[7].min = 1
* differential.element[7].max = "1"
* differential.element[7].type.code = #string
* differential.element[8].id = "t.co"
* differential.element[8].path = "t.co"
* differential.element[8].short = "Country of Test"
* differential.element[8].definition = "Country of Test"
* differential.element[8].min = 1
* differential.element[8].max = "1"
* differential.element[8].type.code = #code
* differential.element[9].id = "t.is"
* differential.element[9].path = "t.is"
* differential.element[9].short = "Certificate Issuer"
* differential.element[9].definition = "Certificate Issuer"
* differential.element[9].min = 1
* differential.element[9].max = "1"
* differential.element[9].type.code = #string
* differential.element[10].id = "t.ci"
* differential.element[10].path = "t.ci"
* differential.element[10].short = "Unique Certificate Identifier, UVCI"
* differential.element[10].definition = "Unique Certificate Identifier, UVCI"
* differential.element[10].min = 1
* differential.element[10].max = "1"
* differential.element[10].type.code = #string
